jump-dev/NLopt.jl

- deps/build.jl
alternate fix for #48 that leaves in place the BinDeps messiness
(another alternative would be to repackage the zip files including an internal folder rather than dumping everything into the current directory, then go with a slightly modified version of #49)
~~edit: will squash if wanted, once I get something that works~~ done
edit2: powershell to the rescue as the only sane shell environment that's installed by default on windows. fixes #48, closes #49
> shell out to powershell rather than coreutils cp on Windows

- README.md
- REQUIRE
- test/tutorial_jump.jl
MathProgBase 0.5 was just tagged, though it doesn't require any changes for nonlinear solvers. Also updated the syntax in the JuMP examples.
> bump MathProgBase requires and update JuMP syntax

- README.md
I thought it looked weird that only parts of the README used the markdown Julia syntax highlighting. Is this intentional?
> Julia syntax highlighting on code in README

- .travis.yml
- appveyor.yml
- src/NLopt.jl
- src/NLoptSolverInterface.jl
Made changes due to deprecation warnings I was getting for Julia v0.6
> Fix deprecation warnings for Julia v0.6

- deps/build.jl
Fixes #84 for me. I guess nlopt moved from homebrew/science to homebrew/core.
> use homebrew/core/nlopt

- .travis.yml
The build was failing on Travis because it was trying to install NLopt via apt-get and then failed because `sudo` was disabled on Travis.
> Fix Travis on Linux

- README.md
- src/NLopt.jl
- test/tutorial.jl
`numevals(opt)` function, AGS global optimizer, and more informative error messages.
Also switched to using proper `@enum` enumerated types in Julia, though `optimize(...)` still returns a symbol for backward compatibility (for now).
> use new features in NLopt 2.5

- README.md
- src/NLopt.jl
- test/tutorial.jl
This lets you do things like `o.maxeval = 1000` instead of `maxeval!(o, 1000)`.   Eventually, my plan is to deprecate the latter functions.
> use dot overloading in 0.7

- README.md
README.md mentions `get_initial_step` function, which should be `initial_step`.
> rename `get_initial_step` in README.md

- src/NLopt.jl
The interop here depends on `Callback_Data` objects being heap allocated with stable addresses, so they need to be mutable. I believe this should be backwards-compatible, but will be necessary in the future (https://github.com/JuliaLang/julia/pull/34126).
> make `Callback_Data` mutable

- Project.toml
- src/NLopt.jl
- test/tutorial.jl
Exposes an `opt.params` dictionary-like interface for the new algorithm-parameters API in NLopt 2.7 (stevengj/nlopt#365)
> new algorithm-parameter API

- src/NLopt.jl
- test/fix133.jl
- test/runtests.jl
Proposed fix for issue #133 
The purpose of this pull request is to fix issue #133. Currently, `remove_constraints!(opt)` produces the following error:
```julia
UndefVarError: chkn not defined
Stacktrace:
[1] remove_constraints!(::Opt) at /Users/myname/.julia/packages/NLopt/eqN9a/src/NLopt.jl:457
[2] top-level scope at In[13]:1
```
The problem is that there is no function named `chkn`.
It appears that the intention of the missing function is to check for any errors thrown by NLopt. The function `chk` already does this. Therefore, I have simply redefined `remove_constraints!` to use `chk` instead of `chkn`. 
I have also included a test file, `fix133.jl`, where I test `remove_constraints!(::Opt)`.
Please note that I'm not a Julia expert and this is my first ever pull request. So, I'm not …
> Fix #133, remove_constraints!(opt) doesn't work; chkn() not defined

- README.md
There are a few typos in the JuMP example; fixing them allowed me to run the example and obtain the expected results.
Fixes #165
> Fix typo in JuMP example

- src/MOI_wrapper.jl
I based this part on the MPB wrapper. They seem to be missing the MPB wrapper as well but there isn't much point updated it as MPB is deprecated now, we even allow solvers to drop their MPB wrappers now.
Closes https://github.com/JuliaOpt/NLopt.jl/issues/160
> Handle missing result status in MOI wrapper

- README.md
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
- test/runtests.jl
It's a bit unfortunate that the number of variables should be set in order to parameterize the local solver. Is there a workaround ?
Closes https://github.com/JuliaOpt/NLopt.jl/issues/126#issuecomment-882081623
> Implement local_optimizer for MOI interface

- README.md
Hello,
I suspect that the template function definitions for the objective and vectorized constraints functions (`f` and `c`) were ported from Python since they include trailing colons (":"). Same on `if` statements. This pull request removes these characters and closes the if statemend with `end`.
Best,
Pierre
> Remove trailing colon in function definitions in README.md

- test/MOI_wrapper.jl
The `opt` variable referred to here is actually defined in the `test/fix133.jl` file.
> Remove useless line in test

- .JuliaFormatter.toml
- .gitignore
- Project.toml
- src/MOI_wrapper.jl
- test/MOI_wrapper.jl
Closes https://github.com/JuliaOpt/NLopt.jl/issues/169
> Update support to MOI v1.0

- src/NLopt.jl
When calling `copy(o::Opt)`, access to the `cb` field by the syntax `o.cb` was prevented by `getproperty`, resulting in
```julia
ERROR: type Opt has no readable property cb
```
This should fix the problem (I tried to check with Julia 1.6 and 1.7, but I don't see why it should not work with older versions).
> Fix copying of Opt objects

- ext/NLoptMathOptInterfaceExt.jl
Found by https://github.com/jump-dev/MathOptInterface.jl/pull/2328
(Next version of MOI will add tests for this.)
> Fix MOI.get for MOI.ConstraintFunction

- Project.toml
- src/NLopt.jl
> predeclare global used in extension

- src/NLopt.jl
- test/runtests.jl
Currently, when a `Symbol` is passed to the `Opt` constructor or the `algorithm_name` function, the corresponding `Algorithm` object is obtained via a `Dict` lookup inside of a `try`/`catch`, where the `catch` permits throwing a more informative error. The use of exception handling here isn't necessary though; rather than using `getindex` and catching any resulting exception, we can instead use `get` with a default value that does not correspond to a valid algorithm and check for equality with that. (Alternatively we could guard the `getindex` with a `haskey` but that requires performing the lookup twice.) This change to using `get` is implemented here.
To avoid duplicating the code that checks a `Symbol` for validity as an algorithm across multiple functions, I've defined a constructor …
> Avoid exception handling for verifying algorithm validity

- Project.toml
I'm going to argue that https://github.com/JuliaOpt/NLopt.jl/pull/194 is a bug fix, but I'm open to arguments that we should make this v1.1.0.
> Prep for v1.0.2

- src/NLopt.jl
- test/C_API.jl
> Remove chk from optimize to allow failures to return to the user

- Project.toml
- gen/Project.toml
- gen/gen.jl
- gen/generate.toml
- src/NLopt.jl
- src/libnlopt.jl
This PR uses Clang.jl to wrap the `libnlopt.h` header file.
It also gets rid of the various `@eval` and macro definitions. Boring and verbose is better than clever.
> Use Clang.jl to automate C wrapper

- src/NLopt.jl
- test/C_API.jl
We can store the exception in `Opt`. It doesn't need to be a global.
> Remove global nlopt_exception

- README.md
Closes https://github.com/JuliaOpt/NLopt.jl/issues/128
> Add section on automatic differentiation to the README

- ext/NLoptMathOptInterfaceExt.jl
- test/MOI_wrapper.jl
> Add support for MOI.ScalarNonlinearFunction

- Project.toml
- README.md
A big diff: https://github.com/JuliaOpt/NLopt.jl/compare/v1.0.3...master
Highlights:
* Clang used to fully wrap the C API
* Support for ScalarNonlinearFunction in the MOI wrapper
* Many many more tests, so that we now have 100% (excluding 1 `@static` line) code coverage
* All backwards compatible with no breaking changes
Since I've been making quite a few changes, I'll hold off on merging this until I get a few people to check it over.
> Prep for v1.1.0

- Project.toml
Marking this as a bug-fix because it restores previous behavior that was unintentionally removed.
> Prep for v1.1.1

- README.md
This came up on slack, and there are multiple issues about it (e.g., #16).
> [README] add example of how to trace iterations

- src/NLopt.jl
- src/libnlopt.jl
- test/C_API.jl
#251 is only needed for 2.9, and is longer needed in NLopt 2.10 (https://github.com/stevengj/nlopt/pull/587 — which should be out soon on Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/10431).
> rewrite NLopt 2.9 workaround for NLopt 2.10

- src/NLopt.jl
Just as an optimization. I don't think in practice this will cause any crashes but it saves one allocation when it's unnecessary and it's being done for the other callback below already.
> Do not wrap NULL pointer in array
